import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";

import { Providers } from "@/components/providers";
import { ssrConfig } from "@/lib/wagmi-ssr";

import "./globals.css";

/**
 * Inter stands in for the brand face, vendored rather than fetched.
 *
 * `next/font/google` self-hosts the result, which is what the CSP needs — but it downloads the files
 * from fonts.googleapis.com *at build time*. That makes the build depend on Google being reachable,
 * and a clean-room reproduction failed exactly there. Committing the two files it actually uses makes
 * the build hermetic: it now works offline, in a sandboxed CI, and when Google has a bad minute.
 *
 * Only the latin subset of weights 400 and 500, because that is all the design system uses. Shipping
 * 600+ would be dead weight and an invitation to break the weight ceiling. Inter is SIL OFL 1.1; the
 * licence sits beside the files.
 */
const inter = localFont({
  src: [
    { path: "../fonts/Inter-400.woff2", weight: "400", style: "normal" },
    { path: "../fonts/Inter-500.woff2", weight: "500", style: "normal" },
  ],
  variable: "--font-inter",
  display: "swap",
  fallback: ["ui-sans-serif", "system-ui", "-apple-system", "Segoe UI", "Roboto", "sans-serif"],
});

const SITE_URL = "https://serein.timjosh507.workers.dev";
const DESCRIPTION =
  "Save private test USDC into a shared prize pool on Sepolia. Your balance and odds stay encrypted, your chance to win stays mathematically fair, and your principal stays withdrawable.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Serein — Private savings. Fair prizes.",
    template: "%s · Serein",
  },
  description: DESCRIPTION,
  applicationName: "Serein",
  openGraph: {
    title: "Serein — Private savings. Fair prizes.",
    description:
      "Confidential no-loss prize savings with encrypted time-weighted balances and exact weighted draws.",
    url: SITE_URL,
    siteName: "Serein",
    type: "website",
    // Generated by `opengraph-image.tsx` — every page inherits this unless it sets its own, so a
    // link to any route on the site renders the same clean preview rather than a blank card.
    images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: "Serein" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Serein — Private savings. Fair prizes.",
    description: DESCRIPTION,
    images: ["/opengraph-image"],
  },
  robots: { index: true, follow: true },
};

export const viewport: Viewport = {
  themeColor: "#221d1d",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  /**
   * Recover the wallet connection from the request cookie.
   *
   * Without this the server renders every page as disconnected and the browser only reconnects after
   * mount, so a refresh or a navigation flashes the "Connect wallet" screen before snapping back —
   * which reads as "I have to connect again" even though nothing was actually lost. Handing the
   * server the real state makes the first paint correct.
   */
  const initialState = cookieToInitialState(ssrConfig, (await headers()).get("cookie"));

  return (
    <html lang="en" className={inter.variable}>
      <body>
        {/* Keyboard users should not have to tab through the whole nav on every page. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-[100] focus:rounded-pill focus:bg-violet focus:px-5 focus:py-3 focus:text-small focus:font-medium focus:text-white"
        >
          Skip to content
        </a>
        <Providers initialState={initialState}>{children}</Providers>
      </body>
    </html>
  );
}
