/**
 * Extract the ABIs the app needs from the compiled artifacts.
 *
 * The generated file is committed so the web build does not depend on Hardhat artifacts being
 * present, and regenerating it after a contract change is a visible diff rather than an invisible
 * drift. `pnpm check` regenerates and fails if the committed copy is stale.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ARTIFACT_ROOT = resolve(process.cwd(), "../contracts/artifacts/contracts");

const TARGETS = [
  { name: "SereinPool", path: "SereinPool.sol/SereinPool.json" },
  { name: "SereinPrizeReserve", path: "SereinPrizeReserve.sol/SereinPrizeReserve.json" },
  { name: "MockPrizeSource", path: "MockPrizeSource.sol/MockPrizeSource.json" },
  { name: "TestUSDC", path: "tokens/TestUSDC.sol/TestUSDC.json" },
  { name: "ConfidentialUSDC", path: "tokens/ConfidentialUSDC.sol/ConfidentialUSDC.json" },
] as const;

interface Artifact {
  abi: unknown[];
}

const chunks: string[] = [
  "// Generated by packages/protocol-sdk/scripts/generate-abis.ts — do not edit by hand.",
  "// Regenerate with `pnpm --filter @serein/protocol-sdk generate` after changing a contract.",
  "",
];

for (const target of TARGETS) {
  const artifactPath = resolve(ARTIFACT_ROOT, target.path);
  let artifact: Artifact;
  try {
    artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as Artifact;
  } catch (error) {
    throw new Error(
      `missing artifact for ${target.name} at ${artifactPath}. ` +
        `Run \`pnpm --filter @serein/contracts compile\` first. (${String(error)})`,
    );
  }
  chunks.push(
    `export const ${target.name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
    "",
  );
}

const outDir = resolve(process.cwd(), "src/generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, "abis.ts"), `${chunks.join("\n")}\n`);

console.log(`Wrote ${TARGETS.length} ABIs to packages/protocol-sdk/src/generated/abis.ts`);
